### ISSUE TITLE
What is the project reference?

### ISSUE THREAD

**Issue by Masynchin** [Iltotore/pokemon-free-monads#1]
Hello, @Iltotore!

I came across to this project searching through your work beside Iron. Not so long ago I learned about `Free`-monad, but I don't know anything about `Alpha`, `Beta`, and `Gamma`. Did you invent this up, or you have reference to this technique?

**Comment by Iltotore** [comment]
Hello.

This project is the basis for an article I'm writting on using free monads to define "complex" game logic, as in Pokemon battles. It is inspired by [this article](https://roganmurley.com/2021/12/11/free-monads.html) by Rogan Murley. I found the idea very interesting and unfortunately I have not found any other article showcasing this approach.

As for `Alpha`, `Beta` and `Gamma`, I used the same names as in Rogan Murley's [project](https://github.com/RoganMurley/GALGAGAME/tree/master/server/src/DSL) but I could have named them differently like `PrimitiveDSL`, `RuleDSL` and `ActionDSL`/`ChoiceDSL`.

**Comment by Masynchin** [comment]
@Iltotore, thanks a lot for the article reference! I am looking for the progress in your implementation, would be interesting to see another example, especially in Scala, of this technique. Good luck!

**Comment by Masynchin** [comment]
@Iltotore hello again!

> This project is the basis for an article I'm writting on using free monads to define "complex" game logic

Are you planning to continue your work? Very excited about it 🙂

**Comment by Iltotore** [comment]
Hello. Unfortuantely I don't think I will continue to work on it. A first working version is available on the repository but sadly I will not finish the article.

Maybe in the future when i'll have time and motivation who knows. I stil find the topic very interesting and I think there is potential when combined with effect handlers.

**Comment by Masynchin** [comment]
Talking about effect handlers, you mean IO? Like, to hide impureness of Random in Game. I am investigating this project's codebase, I thought that it can be added via using `StateT[IO, Game, *]` monad as `GameEffect[*]`, am I correct?

**Comment by Iltotore** [comment]
> Talking about effect handlers, you mean IO?

More something like [Kyo](https://getkyo.io) or in a language like [Effekt](https://effekt-lang.org), typically having an effect `PokeBattle` or similar and "effectful" methods like `damage`, `heal` etc.
